using System.Collections;
using UnityEngine;
using UnityEngine.SocialPlatforms;


public static class Names
{
    public static string GetRandomName()
    {
        return NAMES[Random.Range(0, NAMES.Length)];
    }

    public static string[] NAMES =
   {
            "lilos",
            "Nick",
            "John",
            "Ivan",
            "Tony Mont",
            "Fun Orange",
            "Fast Eagle",
            "MC Mlr",
            "Punisher",
            "Aspect",
            "Bender",
            "Big Papa",
            "Bowser",
            "Bruise",
            "Cannon",
            "Clink",
            "Cobra",
            "Colt",
            "Crank",
            "Creep",
            "Daemon",
            "Decay",
            "Diablo",
            "Doom",
            "Dracula",
            "Dragon",
            "Fender",
            "Fester",
            "Fisheye",
            "Flack",
            "Gargoyle",
            "Grave",
            "Gunner",
            "Hash",
            "Hashtag",
            "Indominus",
            "Ironclad",
            "Killer",
            "Knuckles",
            "Kraken",
            "Lynch",
            "Mad Dog",
            "O'Doyle",
            "Psycho",
            "Ranger",
            "Ratchet",
            "Reaper",
            "Rigs",
            "Ripley",
            "Roadkill",
            "Ronin",
            "Rubble",
            "Sasquatch",
            "Scar",
            "Shiver",
            "Skinner",
            "Skull Crusher",
            "Slasher",
            "Steelshot",
            "Surge",
            "Sythe",
            "Trip",
            "Trooper",
            "Tweek",
            "Vein",
            "Void",
            "Wardon",
            "Wraith",
            "Zero",
            "Steel",
            "Tito",
            "Titanium",
            "Iron-Cut",
            "Steel Forge",
            "Kevlar",
            "Bullet-Proof",
            "Hurricane",
            "Tempest",
            "Pursuit",
            "Lightning",
            "Fire-Bred",
            "Ironsides",
            "Iron Heart",
            "Steel Foil",
            "Upsurge",
            "Breaker",
            "Subversion",
            "Uprising",
            "Sabotage",
            "Rebellion",
            "Overthrow",
            "Dissent",
            "Insurgent",
            "Loch",
            "Rex",
            "Balrog",
            "Basilisk",
            "Cerberus",
            "Charybdis",
            "Cyclops",
            "Golem",
            "Hydra",
            "Manticore",
            "Minotaur",
            "Mothman",
            "Orthros",
            "Satyr",
            "Wendigo",
            "Behemoth",
            "Gorgon",
            "Leviathan",
            "Sylla",
            "Baal",
            "Azrael",
            "Ballistic",
            "Fury",
            "Wrath",
            "Rage",
            "Frenzy",
            "Furor",
            "Ire",
            "Madness",
            "Savage",
            "Mania",
            "Uproar",
            "Demented",
            "Schizo",
            "Manic",
            "Derange",
            "V",
            "Terminator",
            "Siddhartha",
            "Thor",
            "Khan",
            "Leonidas",
            "Hannibal",
            "Agrippa",
            "Atilla",
            "Conqueror",
            "Suleiman",
            "Napoleon",
            "Geronimo",
            "Dutch",
            "Dux",
            "Jesse James",
            "Darko",
            "Mad Max",
            "Billy the Butcher",
            "Maximus",
            "Leon",
            "Cyrus",
            "Mr. Blonde",
            "Matrix",
            "Bleed",
            "Nail",
            "Fist",
            "Tooth",
            "K-9",
            "Kneecap",
            "Soleus",
            "Blood",
            "X-Skull",
            "Jawbone",
            "Skeleton",
            "Craniax",
            "Bone",
            "Cut",
            "Gash",
            "Scab",
            "Gut",
            "Socket",
            "Footslam",
            "Head-Knocker",
            "Razor",
            "Slaughter",
            "Scalp",
            "Torque",
            "Wracker",
            "Wrecker",
            "Clencher",
            "Masher",
            "Crusher",
            "Slammer",
            "Thrasher",
            "Annihilator",
            "Destroyer",
            "Stabber",
            "Hitter",
            "Obliterator",
            "Exterminator",
            "Ruiner",
            "Finisher",
            "Overtaker",
            "Saboteur",
            "Rebel",
            "Eliminator",
            "Hell-Raiser",
            "Mutant",
            "Torpedo",
            "Cannon",
            "Mortar",
            "Siege",
            "Bullet",
            "Aero",
            "Albatross",
            "Arsenal",
            "Hornet",
            "Wildcat",
            "Hellcat",
            "Tomcat",
            "Panther",
            "Jaguar",
            "Bomber",
            "Strike Eagle",
            "Rimfire",
            "Centerfire",
            "Automatic",
            "Glock",
            "Sniper",
            "Carbine",
            "Javelin",
            "Howitzer",
            "Gatling",
            "Avenger",
            "Hazzard",
            "Demolition",
            "Chainsaw",
            "Wrench",
            "Power Train",
            "Excavator",
            "Shovel",
            "Yarder",
            "Trencher",
            "Pile Driver",
            "Terror",
            "Freak",
            "Axe",
            "Axe-man",
            "Executioner",
            "Hollowman",
            "Garrot",
            "Abyss",
            "Chasm",
            "Ghoul",
            "Demise",
            "Grim",
            "Menace",
            "Dementor",
            "Nightshade",
            "Venom",
            "The Unholy",
            "Rot",
            "Omen",
            "Midnight",
            "Phantom",
            "Sepulcher",
            "Damned",
            "Kafka",
            "Phantasm",
            "Scream",
            "Shriek",
            "Wraith",
            "Bodybag",
            "Morgue"
    };
}

